"""Step 4 - Streamlit UI: pick a notebook -> parse -> generate 3 cited docs -> click a cite to see the code."""
from pathlib import Path

import streamlit as st

from harness import DOCS, generate, load_config, ref, to_markdown
from notebook import parse

DEFAULT = Path(__file__).resolve().parent.parent / "cash_application_engine.py"

st.set_page_config(page_title="Notebook Explainer", page_icon="📓", layout="wide")
cfg = load_config()
st.title("📓 Notebook Explainer")
st.caption(f"Model `{cfg['model']}` · switch in `app/config.yaml` or env `HARNESS_MODEL`")


@st.cache_data(show_spinner=False)
def cached_generate(path: str, mtime: float, audience: str, model: str) -> dict:
    return generate(parse(path), audience, cfg)


def snippet(cell, cite, context=2):
    lo, hi = cite["start"], cite["end"]
    return "\n".join(f"{'▶' if lo <= n <= hi else ' '} {n:>4} | {t}"
                     for n, t in cell.lines.items() if lo - context <= n <= hi + context)


# 1. Pick + parse
path = Path(st.text_input("Notebook file on disk (.py Databricks source or .ipynb)", str(DEFAULT))).expanduser()
if not path.is_file():
    st.warning("File not found.")
    st.stop()
cells = parse(path)
index = {c.id: c for c in cells}
with st.expander(f"① Parsed {len(cells)} cells - see how the notebook was split"):
    st.dataframe([{"cell": c.id, "kind": c.kind, "lines": f"L{c.start}-L{c.end}",
                   "first line": next(t for t in c.lines.values() if t.strip())[:90]} for c in cells],
                 hide_index=True)

# 2. Generate
if st.session_state.get("path") != str(path):
    st.session_state.update(path=str(path), docs={})
if st.button("② Generate the 3 documents", type="primary"):
    with st.status("Generating…", expanded=True) as status:
        for key, spec in DOCS.items():
            status.write(f"Writing **{spec['title']}** and verifying citations…")
            try:
                st.session_state.docs[key] = cached_generate(str(path), path.stat().st_mtime, key, cfg["model"])
            except Exception as error:  # surface provider/model errors in the UI
                st.session_state.docs[key] = {"error": f"{type(error).__name__}: {error}"}
        status.update(label="Done", state="complete", expanded=False)

# 3. Show docs with clickable cites
for tab, key in zip(st.tabs([f"③ {s['title']}" for s in DOCS.values()]), DOCS):
    with tab:
        doc = st.session_state.docs.get(key)
        if not doc:
            st.info("Click Generate.")
            continue
        if "error" in doc:
            st.error(doc["error"])
            continue
        kept = sum(len(s["claims"]) for s in doc["sections"])
        st.caption(f"Generated by `{doc['model']}` · {kept} verified claims · {len(doc['dropped'])} dropped · "
                   f"{doc['requests']} LLM requests · {doc['tokens']:,} tokens")
        for section in doc["sections"]:
            st.subheader(section["title"])
            for i, claim in enumerate(section["claims"]):
                text_col, cite_col = st.columns([5, 1])
                text_col.markdown(f"- {claim['text']}")
                with cite_col:
                    for j, cite in enumerate(claim["cites"]):
                        with st.popover(ref(cite), width="stretch", key=f"{key}-{section['title']}-{i}-{j}"):
                            cell = index[cite["cell"]]
                            st.caption(f"Cell {cell.id} · {cell.kind} · file lines {cite['start']}-{cite['end']}")
                            st.code(snippet(cell, cite), language="python")
        if doc["dropped"]:
            with st.expander(f"Dropped {len(doc['dropped'])} claims that failed verification"):
                for d in doc["dropped"]:
                    st.markdown(f"- **[{d['section']}]** {d['text']}  \n  ↳ _{'; '.join(d['errors'])}_")
        st.download_button("Download markdown", to_markdown(doc, str(path)), f"{key}.md", key=f"dl-{key}")
